dist: trusty
language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

install:
- composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: composer test
